### ISSUE TITLE
'AttributeError: 'str' object has no attribute 'get' ' while importing bundles.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#101]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/projects/ambry_project/ambry/cli/__main__.py", line 5, in <module>
    main(sys.argv)
  File "/home/nmb10/projects/ambry_project/ambry/cli/__init__.py", line 361, in main
    f(args, rc)
  File "/home/nmb10/projects/ambry_project/ambry/cli/root.py", line 104, in root_command
    l = new_library(rc)
  File "/home/nmb10/projects/ambry_project/ambry/library/__init__.py", line 46, in new_library
    library_config = config.library()
  File "/home/nmb10/projects/ambry_project/ambry/run.py", line 328, in library
    database = e.get('database', '').format(**fs)
  File "/home/nmb10/projects/ambry_project/ambry/run.py", line 389, in database
    config, dsn = normalize_dsn_or_dict(e)
  File "/home/nmb10/projects/ambry_project/ambry/run.py", line 540, in normalize_dsn_or_dict
    up = d.get('username', '') or ''
AttributeError: 'str' object has no attribute 'get'
```

**Comment by ericbusboom** [comment]
What .yaml file is it reading?

**Comment by nmb10** [comment]
This happens because .ambry.yaml contains such block:
```yaml
library:
    default:
        database: sqlite://{root}/library.db
        filesystem: '{root}/library'
        remotes:
            public: http://public.library.civicknowledge.com
            system: http://system.library.civicknowledge.com
```
Ambry should give more informative message if it can't get  valid database from config.

**Comment by nmb10** [comment]
It works after config reinstall:
```bash
ambry config install -f
```
