### ISSUE TITLE
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#102]
```bash
ambry import -d ambry_project/test/bundles
```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/projects/ambry_project/ambry/cli/__main__.py", line 5, in <module>
    main(sys.argv)
  File "ambry/cli/__init__.py", line 361, in main
    f(args, rc)
  File "ambry/cli/root.py", line 104, in root_command
    l = new_library(rc)
  File "ambry/library/__init__.py", line 62, in new_library
    search = search_backend)
  File "ambry/library/__init__.py", line 77, in __init__
    self._db.open()
  File "ambry/orm/database.py", line 215, in open
    self.session
  File "ambry/orm/database.py", line 197, in session
    self.Session = sessionmaker(bind=self.engine, expire_on_commit=True)
  File "ambry/orm/database.py", line 178, in engine
    with self._engine.connect() as conn:
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2005, in connect
    return self._connection_cls(self, **kwargs)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2091, in raw_connection
    self.pool.unique_connection, _connection)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2065, in _wrap_pool_connect
    e, dialect, self)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1395, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2061, in _wrap_pool_connect
    return fn()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 279, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 644, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 439, in checkout
    rec = pool._do_get()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1055, in _do_get
    return self._create_connection()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 284, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 410, in __init__
    self.connection = self.__connect()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 538, in __connect
    connection = self.__pool._creator()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 89, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file
```

**Comment by ericbusboom** [comment]
> On Sep 24, 2015, at 9:26 AM, Kazbek <notifications@github.com> wrote:
> 
> ambry import -d ambry_project/test/bundles
> Traceback (most recent call last):

Looks like the library isn’t configured. What does `ambry info` do?

eric. 


----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
The same error.

**Comment by ericbusboom** [comment]
What's your library DSN?

**Comment by nmb10** [comment]
.ambry.yaml
```yaml
...
library:
    database: sqlite://{root}/library.db
```

**Comment by nmb10** [comment]
Ambry was installed it with:
```bash
git clone https://github.com/CivicKnowledge/ambry.git
cd ambry
git checkout ambry1.0
python setup.py develop
```

**Comment by ericbusboom** [comment]
It looks like the problem is that there should be three / before the {root} in for the DSN in the .ambry.yaml file. 

Change: 

    database:
        sqlite: 'sqlite://{root}/ambry.db'

to 

    database:
        sqlite: 'sqlite:///{root}/ambry.db'

**Comment by nmb10** [comment]
Yes, it was exactly that case. Fixed.
