### ISSUE TITLE
'TypeError: string indices must be integers, not str' error while config installation.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#103]
Remove (or rename) existing .ambry.yaml, run:
```bash
ambry config install
```
Writing config file: /home/nmb10/.virtualenvs/ambry/.ambry.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/projects/ambry_project/ambry/cli/__main__.py", line 5, in <module>
    main(sys.argv)
  File "ambry/cli/__init__.py", line 361, in main
    f(args, rc)
  File "ambry/cli/config.py", line 56, in config_command
    globals()['config_' + args.subcommand](args, l, rc)
  File "ambry/cli/config.py", line 161, in config_install
    dr = fs['dir']
TypeError: string indices must be integers, not str

**Comment by nmb10** [comment]
Ambry was installed with:
```bash
git clone https://github.com/CivicKnowledge/ambry.git
cd ambry
git checkout ambry1.0
python setup.py develop
```

**Comment by ericbusboom** [comment]
I just fixed some of these issues on the develop branch. There was very poor handling of missing configs. 

You should delete ~/.ambry.yaml. Then, when you install to a new virtualenv, it will prompt you to run `ambry config install`, which will create a new .ambry.yaml in the virtualenv.  Your .ambry-accounts.yaml should stay outside of the virtualenv.

**Comment by nmb10** [comment]
It works now.
