### ISSUE TITLE
Post-build phase, stage main failed: (pysqlite2.dbapi2.OperationalError) table dataset_index already exists

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#105]
```bash
bambry -i d000simple003 ingest
bambry schema
bambry build
```

ERROR example.com-simple Post-build phase, stage main failed: (pysqlite2.dbapi2.OperationalError) table dataset_index already exists [SQL: '            CREATE VIRTUAL TABLE dataset_index USING fts3(\n                vid VARCHAR(256) NOT NULL,\n                title TEXT,\n                keywords TEXT,\n                doc TEXT\n            );\n        ']
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/projects/ambry_project/ambry/cli/__main__.py", line 5, in <module>
    main(sys.argv)
  File "/home/nmb10/projects/ambry_project/ambry/cli/__init__.py", line 363, in main
    f(args, rc)
  File "/home/nmb10/projects/ambry_project/ambry/cli/bundle.py", line 44, in bundle_command
    globals()['bundle_' + args.subcommand](args, l, rc)
  File "/home/nmb10/projects/ambry_project/ambry/cli/bundle.py", line 669, in bundle_build
    b.build(sources=sources, force = args.force)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 1268, in build
    return self.run_phase('build', sources=sources, stage=stage, force = force)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 1190, in run_phase
    phase_post()
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 1287, in post_build
    self.library.search.index_bundle(self, force = True)
  File "/home/nmb10/projects/ambry_project/ambry/library/__init__.py", line 520, in search
    self._search = Search(self)
  File "/home/nmb10/projects/ambry_project/ambry/library/search.py", line 37, in __init__
    backend = BACKENDS[backend_name](library)
  File "/home/nmb10/projects/ambry_project/ambry/library/search_backends/base.py", line 149, in __init__
    self.dataset_index = self._get_dataset_index()
  File "/home/nmb10/projects/ambry_project/ambry/library/search_backends/sqlite_backend.py", line 24, in _get_dataset_index
    return DatasetSQLiteIndex(backend=self)
  File "/home/nmb10/projects/ambry_project/ambry/library/search_backends/sqlite_backend.py", line 68, in __init__
    self.backend.library.database.connection.execute(query)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) table dataset_index already exists [SQL: '            CREATE VIRTUAL TABLE dataset_index USING fts3(\n                vid VARCHAR(256) NOT NULL,\n                title TEXT,\n                keywords TEXT,\n                doc TEXT\n            );\n        ']

**Comment by nmb10** [comment]
Fixed.
