### ISSUE TITLE
Running ampr without arguments raises an error. It should print help instead.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#106]
see [Check your Work](http://ambry.readthedocs.org/en/ambry1.0/tutorial/example_bundles.html#check-your-work) for ampr command.

```bash
$ ampr
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/.virtualenvs/ambry/lib/python2.7/site-packages/ambry_sources/__main__.py", line 9, in <module>
    main()
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/cli.py", line 46, in main
    f = MPRowsFile(args.path)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/mpf.py", line 167, in __init__
    self._fs, self._path = opener.parse(url_or_fs)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/fs/opener.py", line 206, in parse
    match = self.split_segments(fs_url)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/fs/opener.py", line 167, in split_segments
    match = self.re_fs_url.match(fs_url)
TypeError: expected string or buffer

**Comment by ericbusboom** [comment]
This is actually an issue for the ambry-sources repo; it's closed by commit CivicKnowledge/ambry_sources@79848963d97f873f939c250b26706351f9a0ecb1
