### ISSUE TITLE
'TypeError: 'NoneType' object is not callable' while getting s3 source.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#109]
Ambry does not give s3 credentials to the ambry_sources.
```
Traceback (most recent call last):
  File "load_pre10.py", line 192, in <module>
    main()
  File "load_pre10.py", line 181, in main
    _ingest(b)
  File "load_pre10.py", line 120, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 874, in ingest
    s = get_source(source.spec, self.library.download_cache, clean=force)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 37, in get_source
    cache_path, download_time = download(spec.url, cache_fs, account_accessor, clean=clean)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 200, in download
    s3 = get_s3(url, account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 266, in get_s3
    
TypeError: 'NoneType' object is not callable
```

**Comment by nmb10** [comment]
I fixed it. Waiting for ambry_sources 0.0.8 on pypi.

**Comment by ericbusboom** [comment]
> On Oct 3, 2015, at 5:25 AM, Kazbek <notifications@github.com> wrote:
> 
> I fixed it. Waiting for ambry_sources 0.0.8 on pypi.

I just published it to pypi.

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Done.
