### ISSUE TITLE
sangis.org-places-orig.yaml import error: DownloadError: Failed to download http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip; 404 Client Error: Not Found

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#115]
run:
```bash
python load_pre10.py ../../pre-10-bundles/converted/sangis.org-places-orig/sangis.org-places-orig.yaml 
```

error:
```
Starting import ../../pre-10-bundles/converted/sangis.org-places-orig/sangis.org-places-orig.yaml...
Loading bundle: sangis.org-places-orig-0.1.2~d00R002
INFO sangis.org-places-orig ---- Synchronized ----
Starting ingest...
INFO sangis.org-places-orig Ingesting: cities from http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip
Traceback (most recent call last):
  File "load_pre10.py", line 251, in <module>
    main()
  File "load_pre10.py", line 220, in main
    _ingest(b)
  File "load_pre10.py", line 177, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 873, in ingest
    clean=force, account_accessor=account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 45, in get_source
    raise DownloadError("Failed to download {}; {}".format(spec.url, e))
ambry_sources.exceptions.DownloadError: Failed to download http://rdw.sandag.org/file_store/Jurisdiction/Municipal_Boundaries.zip; 404 Client Error: Not Found
```

**Comment by ericbusboom** [comment]
Closed by #122; just set an error, viewable in `ambry list`, and handle the problem manually.
