### ISSUE TITLE
oshpd.ca.gov-facilities.yaml import error: DownloadError: Failed to download http://www.oshpd.ca.gov/HID/Products/FacilityList/2014/Home-Health-Agencies-and-Hospice-Listing-2014.xlsx; 404 Client Error: Not Found

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#116]
run:
```bash
python load_pre10.py ../../pre-10-bundles/converted/oshpd.ca.gov-facilities/oshpd.ca.gov-facilities.yaml 
```

error:
```
Starting import ../../pre-10-bundles/converted/oshpd.ca.gov-facilities/oshpd.ca.gov-facilities.yaml...
Loading bundle: oshpd.ca.gov-facilities-0.0.8~d03j008
INFO oshpd.ca.gov-facilities ---- Synchronized ----
Starting ingest...
INFO oshpd.ca.gov-facilities Ingesting: hospice_2013 from http://www.oshpd.ca.gov/HID/Products/FacilityList/HHAListing_Dec2013.xlsx
INFO oshpd.ca.gov-facilities Ingested: hospice_2013.mpr
INFO oshpd.ca.gov-facilities Ingesting: hospice_2014 from http://www.oshpd.ca.gov/HID/Products/FacilityList/2014/Home-Health-Agencies-and-Hospice-Listing-2014.xlsx
Traceback (most recent call last):
  File "load_pre10.py", line 251, in <module>
    main()
  File "load_pre10.py", line 220, in main
    _ingest(b)
  File "load_pre10.py", line 177, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 873, in ingest
    clean=force, account_accessor=account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 45, in get_source
    raise DownloadError("Failed to download {}; {}".format(spec.url, e))
ambry_sources.exceptions.DownloadError: Failed to download http://www.oshpd.ca.gov/HID/Products/FacilityList/2014/Home-Health-Agencies-and-Hospice-Listing-2014.xlsx; 404 Client Error: Not Found
```

**Comment by ericbusboom** [comment]
Closed by #122; just set an error, viewable in `ambry list`, and handle the problem manually.
