### ISSUE TITLE
sandiegodata.org.crime-201303.yaml import error: NotObjectNumberError: Unknown type character 'a' for '2pN5m'

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#118]
run:
```bash
python load_pre10.py ../../pre-10-bundles/converted/sandiegodata.org.crime-201303/sandiegodata.org.crime-201303.yaml
```

error:
```
Starting import ../../pre-10-bundles/converted/sandiegodata.org.crime-201303/sandiegodata.org.crime-201303.yaml...
Traceback (most recent call last):
  File "load_pre10.py", line 251, in <module>
    main()
  File "load_pre10.py", line 219, in main
    b = _import(args[0])
  File "load_pre10.py", line 129, in _import
    b = library.new_from_bundle_config(config)
  File "/home/nmb10/projects/ambry_project/ambry/library/__init__.py", line 202, in new_from_bundle_config
    identity = Identity.from_dict(config['identity'])
  File "/home/nmb10/projects/ambry_project/ambry/identity.py", line 1282, in from_dict
    ono = ObjectNumber.parse(d['id'])
  File "/home/nmb10/projects/ambry_project/ambry/identity.py", line 757, in parse
    raise NotObjectNumberError("Unknown type character '{}' for '{}'".format(type_, on_str))
ambry.identity.NotObjectNumberError: Unknown type character 'a' for '2pN5m'
```

**Comment by ericbusboom** [comment]
Moved to CivicKnowledge/pre-10-bundles#8
