### ISSUE TITLE
oshpd.ca.gov-msdgr-top25.yaml import error: SourceError: Failed to determine file type for source '2008Top25MSDRG_Pivot'; unknown type 'xlsm'

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#119]
run:
```bash
python load_pre10.py ../../pre-10-bundles/converted/oshpd.ca.gov-msdgr-top25/oshpd.ca.gov-msdgr-top25.yaml
```

error:
```
Starting import ../../pre-10-bundles/converted/oshpd.ca.gov-msdgr-top25/oshpd.ca.gov-msdgr-top25.yaml...
Loading bundle: oshpd.ca.gov-msdgr-top25-0.0.3~d03P003
INFO oshpd.ca.gov-msdgr-top25 ---- Synchronized ----
Starting ingest...
INFO oshpd.ca.gov-msdgr-top25 Ingesting: 2008Top25MSDRG_Pivot from http://www.oshpd.ca.gov/HID/Products/PatDischargeData/PivotTables/Top25DRGs/2008Top25MSDRG_Pivot.xlsm
INFO oshpd.ca.gov-msdgr-top25 Downloading http://www.oshpd.ca.gov/HID/Products/PatDischargeData/PivotTables/Top25DRGs/2008Top25MSDRG_Pivot.xlsm
Traceback (most recent call last):
  File "load_pre10.py", line 251, in <module>
    main()
  File "load_pre10.py", line 220, in main
    _ingest(b)
  File "load_pre10.py", line 177, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 873, in ingest
    clean=force, account_accessor=account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 76, in get_source
    .format(spec.name, file_type))
ambry_sources.sources.exceptions.SourceError: Failed to determine file type for source '2008Top25MSDRG_Pivot'; unknown type 'xlsm'
```

**Comment by ericbusboom** [comment]
Moved to CivicKnowledge/pre-10-bundles#5
