### ISSUE TITLE
Automatic detection of shapefiles. 

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#121]
run:
```bash
python load_pre10.py ../../pre-10-bundles/converted/civicsd.org-neighborhoods/civicsd.org-neighborhoods.yaml
```

error:
```
Starting import ../../pre-10-bundles/converted/civicsd.org-neighborhoods/civicsd.org-neighborhoods.yaml...
Loading bundle: civicsd.org-neighborhoods-0.0.2~d035002
INFO civicsd.org-neighborhoods ---- Synchronized ----
Starting ingest...
INFO civicsd.org-neighborhoods Ingesting: neighborhoods from http://ds.civicknowledge.org/civicsd.com/neighborhood.zip
Traceback (most recent call last):
  File "load_pre10.py", line 253, in <module>
    main()
  File "load_pre10.py", line 222, in main
    _ingest(b)
  File "load_pre10.py", line 179, in _ingest
    b.ingest(force=force, clean_files=clean_files)
  File "/home/nmb10/projects/ambry_project/ambry/bundle/bundle.py", line 873, in ingest
    clean=force, account_accessor=account_accessor)
  File "/home/nmb10/.virtualenvs/ambry/local/lib/python2.7/site-packages/ambry_sources/download.py", line 76, in get_source
    .format(spec.name, file_type))
ambry_sources.sources.exceptions.SourceError: Failed to determine file type for source 'neighborhoods'; unknown type 'dbf' 
```

**Comment by ericbusboom** [comment]
The file, http://ds.civicknowledge.org/civicsd.com/neighborhood.zip is a shapefile, but since that isn't noted in the sources, ambry reads the first file, which is a .dbf.

**Comment by ericbusboom** [comment]
See also: CivicKnowledge/pre-10-bundles#6

**Comment by ericbusboom** [comment]
Actually, don't auto detect; just mark this particular source as a shapefile. Moved to: CivicKnowledge/pre-10-bundles#6
