### ISSUE TITLE
3 Tests Failing in ambry/test/test_library/functional/test_search_backends.py

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/ambry#130]
There are three tests failing in test_search_backends.py:

test_search.py

    Failure
    Traceback (most recent call last):
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 263, in test_search_by
        self._assert_finds_partition(partition, 'by county')
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 38, in _assert_finds_partition
        self.assertIn(partition.vid, all_vids)
    AssertionError: u'p000000001003001' not found in []
    
test_search_dataset_by_source

    Failure
    Traceback (most recent call last):
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 86, in test_search_dataset_by_source
        self._assert_finds_dataset(dataset, 'source example.com')
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 33, in _assert_finds_dataset
        self.assertIn(dataset.vid, all_vids)
    AssertionError: u'd000000001001' not found in []
 
test_search_in.py
    
    Failure
    Traceback (most recent call last):
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 244, in test_search_in
        self._assert_finds_partition(partition, 'in California')
      File "/Users/eric/proj/virt/ambry-develop/ambry/test/test_library/functional/test_search_backends.py", line 38, in _assert_finds_partition
        self.assertIn(partition.vid, all_vids)
    AssertionError: u'p000000001004001' not found in []

**Comment by nmb10** [comment]
No errors for me:
```bash
py.test test/test_library/functional/test_search_backends.py --verbose
===== 63 passed in 56.43 seconds =======
```
What tests are broken exactly? You can use --verbose option for detailed output.

**Comment by ericbusboom** [comment]
test_search_by
test_search_dataset_by_source
test_search_in

**Comment by nmb10** [comment]
These tests are shared between some backends:
```
WhooshBackendTest::test_search_by
SQLiteBackendTest::test_search_by
PostgreSQLBackendTest::test_search_by
```
 Which backend tests are broken?

**Comment by ericbusboom** [comment]
> On Oct 20, 2015, at 8:26 AM, Kazbek <notifications@github.com> wrote:
> 
> These tests are shared between some backends:
> 
> WhooshBackendTest::test_search_by
> SQLiteBackendTest::test_search_by
> PostgreSQLBackendTest::test_search_by
> Which backend tests are broken
> 
> 

Sqlite. 



----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by nmb10** [comment]
Can you update code and try again? There are some changes from other issue.

**Comment by ericbusboom** [comment]
Ok, but it may take a while, as there are currently a lot of tests failing.
