### ISSUE TITLE
Missing whoosh in requirements.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#20]
```python
import ambry
l = ambry.library()
results = [
    (name, gvid) for score, gvid, name in l.search.search_identifiers('C')]
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/library/__init__.py", line 1408, in search
    from search import Search
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/library/search.py", line 5, in <module>
    from whoosh.fields import SchemaClass, TEXT, KEYWORD, ID, STORED, DATETIME, NGRAMWORDS, NGRAM

**Comment by nmb10** [comment]
Fixed in the 4733ac4
